### PR TITLE
License

### PR DESCRIPTION
**Pull request by wlandau**
This PR adds the license back to each individual code file you developed, and it adds a `LICENSE.note` to put ownership and responsibility on the individual package authors.

### CODE REVIEW

**Review by shikokuchuo — CHANGES_REQUESTED** [review]
I think there's no harm leaving the `snapshot.url` behind for easier troubleshooting.

Now that I'm forced to think about this, I don't think either of the files are subject to copyright. The html certainly is not as it is just one sentence on a base html spec. The workflow file, if it is, it is up to Jeroen as it is heavily derivative of his work https://github.com/jeroen/backup/ which I had noted before.

I'm fine with adding the LICENCE.note if you think that's helpful.

**Comment by wlandau** [comment]
> I'm fine with adding the LICENCE.note if you think that's helpful.

`LICENCE.note` is by far the most important piece because it emphasizes that we don't own the packages.

> Now that I'm forced to think about this, I don't think either of the files are subject to copyright. The html certainly is not as it is just one sentence on a base html spec.

Even so, it's a file in an OSS project that carries a lot of risk. I think it's important to make licensing and copyright perfectly clear and airtight even in these small cases.

> The workflow file, if it is, it is up to Jeroen as it is heavily derivative of his work https://github.com/jeroen/backup/ which I had noted before.

@jeroen, is https://github.com/jeroen/backup/blob/main/.github/workflows/mirror.yml licensed?

> I think there's no harm leaving the snapshot.url behind for easier troubleshooting.

Is it necessary to include? If so, I would like to add a line in `LICENSE.note`.

**Comment by shikokuchuo** [comment]
> > I think there's no harm leaving the snapshot.url behind for easier troubleshooting.
> 
> Is it necessary to include? If so, I would like to add a line in `LICENSE.note`.

A URL is simply factual information and there is no original expression in a file which just contains a URL, hence it does not meet the requirements for copyright as I understand it.

**Comment by wlandau** [comment]
@shikokuchuo, would you take another look? This PR now only adds the MIT license for the workflow file, which @jeroen requested.

**Review by shikokuchuo — APPROVED** [review]

**Pull request merged**
